# Generated by Django 5.1.4 on 2024-12-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='D:\\University\\Final Year Project\\Development\\Code\\DMI_FYP_dj_primary-backend\\DMI_backend\\media/submissions/')),
                ('file_type', models.CharField(default='Video', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='DeepfakeDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deepfake', models.BooleanField(blank=True)),
                ('confidence_score', models.FloatField(blank=True)),
                ('frames_analyzed', models.IntegerField(blank=True)),
                ('fake_frames', models.IntegerField(blank=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_report', models.JSONField(blank=True)),
                ('media_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mediaupload')),
            ],
        ),
    ]
