# Generated by Django 5.1.4 on 2024-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='file_type',
            field=models.CharField(default='Video', max_length=512),
        ),
    ]
