# Generated by Django 5.1.4 on 2024-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mediaupload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='file',
            field=models.FileField(max_length=512, upload_to='D:\\University\\Final Year Project\\Development\\Code\\DMI_FYP_dj_primary-backend\\DMI_backend\\media/submissions/'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='file_type',
            field=models.CharField(default='Video', max_length=32),
        ),
    ]
