# Generated by Django 5.1.4 on 2025-02-06 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mediaupload_file_alter_mediaupload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='file',
            field=models.FileField(max_length=512, upload_to='submissions/'),
        ),
        migrations.CreateModel(
            name='AIGeneratedMediaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_generated', models.BooleanField()),
                ('confidence_score', models.FloatField()),
                ('analysis_report', models.JSONField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('media_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mediaupload')),
            ],
        ),
    ]
