# Generated by Django 5.1.4 on 2025-02-15 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mediaupload_file_aigeneratedmediaresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='file_identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MediaUploadMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('media_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mediaupload')),
            ],
        ),
    ]
