# Generated by Django 5.1.4 on 2025-02-15 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mediaupload_file_identifier_mediauploadmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='original_filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
