# Generated by Django 5.1.4 on 2025-02-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mediaupload_original_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaupload',
            old_name='file_identifier',
            new_name='submission_identifier',
        ),
    ]
