# Generated by Django 5.1.4 on 2025-02-25 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_file_identifier_mediaupload_submission_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='file_identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
