# Generated by Django 5.1.4 on 2025-02-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mediaupload_file_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='purpose',
            field=models.CharField(default='Deepfake-Detection', max_length=32),
        ),
    ]
