# Generated by Django 5.1.4 on 2025-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mediaupload_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='purpose',
            field=models.CharField(default='Deepfake-Analaysis', max_length=32),
        ),
    ]
