# Generated by Django 5.1.4 on 2025-03-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_mediaupload_purpose'),
        ('app', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('submission_identifier', models.CharField(max_length=128)),
                ('purpose', models.CharField(default='AI-Text-Analysis', max_length=32)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='AIGeneratedTextResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_generated', models.BooleanField()),
                ('source_prediction', models.CharField(max_length=32)),
                ('confidence_scores', models.JSONField()),
                ('highlighted_text', models.TextField(blank=True)),
                ('html_text', models.TextField(blank=True)),
                ('word_scores', models.JSONField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('text_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.textsubmission')),
            ],
        ),
    ]
