# Generated by Django 5.1.4 on 2025-03-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_textsubmission_aigeneratedtextresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigeneratedtextresult',
            name='word_scores',
        ),
    ]
