# Generated by Django 5.1.4 on 2025-03-10 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_aigeneratedtextresult_word_scores'),
        ('app', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDeepfakeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pda_submissions/')),
                ('original_filename', models.CharField(max_length=255)),
                ('submission_identifier', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('POL', 'Politician'), ('CEL', 'Celebrity'), ('INF', 'Influencer'), ('PUB', 'Public Figure'), ('OTH', 'Other')], max_length=3)),
                ('context', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('detection_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deepfakedetectionresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
    ]
