# Generated by Django 5.1.4 on 2025-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_publicdeepfakearchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicdeepfakearchive',
            name='context',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='publicdeepfakearchive',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publicdeepfakearchive',
            name='file',
            field=models.FileField(max_length=512, upload_to='pda_submissions/'),
        ),
        migrations.AlterField(
            model_name='publicdeepfakearchive',
            name='original_filename',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='publicdeepfakearchive',
            name='submission_identifier',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='publicdeepfakearchive',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
