# Generated by Django 5.1.4 on 2025-04-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_publicdeepfakearchive_detection_result'),
        ('app', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacialWatchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_confidence', models.FloatField()),
                ('face_location', models.JSONField(null=True)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('media_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mediaupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='FacialWatchRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embedding', models.JSONField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='api_facialw_user_id_a2cde6_idx')],
            },
        ),
    ]
