# Generated by Django 5.1.4 on 2025-04-28 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_facialwatchmatch_facialwatchregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facialwatchmatch',
            name='media_upload',
        ),
        migrations.AddField(
            model_name='facialwatchmatch',
            name='pda_submission_identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
