# Generated by Django 5.1.4 on 2025-04-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_facialwatchmatch_media_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facialwatchmatch',
            name='media_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mediaupload'),
        ),
    ]
