# Generated by Django 5.1.4 on 2025-04-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_facialwatchmatch_media_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facialwatchmatch',
            name='media_upload',
        ),
        migrations.AddField(
            model_name='facialwatchmatch',
            name='pda_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.publicdeepfakearchive'),
        ),
    ]
