# Generated by Django 5.1.4 on 2025-04-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_facialwatchmatch_media_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embedding', models.JSONField()),
                ('face_location', models.JSONField()),
                ('frame_id', models.CharField(max_length=100, null=True)),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('pda_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_faces', to='api.publicdeepfakearchive')),
            ],
            options={
                'indexes': [models.Index(fields=['pda_submission'], name='api_detecte_pda_sub_71bd85_idx')],
            },
        ),
    ]
