# Generated by Django 5.1.4 on 2025-04-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_detectedface'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetectedFace',
            new_name='PDASubmissionProfiledFace',
        ),
        migrations.RenameIndex(
            model_name='pdasubmissionprofiledface',
            new_name='api_pdasubm_pda_sub_53033e_idx',
            old_name='api_detecte_pda_sub_71bd85_idx',
        ),
    ]
