# Generated by Django 5.1.4 on 2025-05-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_forumanalytics_forumtag_forumtopic_forumthread_and_more'),
        ('app', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.forumreply')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.forumthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
            options={
                'indexes': [models.Index(fields=['thread', 'reaction_type'], name='api_forumre_thread__11bafe_idx'), models.Index(fields=['reply', 'reaction_type'], name='api_forumre_reply_i_7c9a6e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('thread__isnull', False)), fields=('user', 'thread', 'reaction_type'), name='unique_thread_reaction_per_user'), models.UniqueConstraint(condition=models.Q(('reply__isnull', False)), fields=('user', 'reply', 'reaction_type'), name='unique_reply_reaction_per_user')],
            },
        ),
    ]
