# Generated by Django 5.1.4 on 2025-05-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_forumreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumlike',
            name='like_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10),
        ),
    ]
