# Generated by Django 5.1.4 on 2025-05-09 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_like_type_to_forumlike'),
        ('app', '0004_userdata_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reply', 'New Reply'), ('like', 'New Like'), ('reaction', 'New Reaction'), ('mention', 'Mention'), ('solution', 'Solution Marked')], max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='forumanalytics',
            options={'verbose_name_plural': 'Forum analytics'},
        ),
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Forum replies'},
        ),
        migrations.AlterModelOptions(
            name='forumtag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-last_active']},
        ),
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='forumlike',
            name='unique_thread_like',
        ),
        migrations.RemoveConstraint(
            model_name='forumlike',
            name='unique_reply_like',
        ),
        migrations.AddField(
            model_name='forumanalytics',
            name='active_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumanalytics',
            name='replies_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumanalytics',
            name='threads_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumanalytics',
            name='total_reactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumanalytics',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumtag',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='forumtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumthread',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forumlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to='app.userdata'),
        ),
        migrations.AlterField(
            model_name='forumreaction',
            name='reaction_type',
            field=models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry'), ('🔥', 'Fire'), ('👏', 'Clap'), ('🧠', 'Brain')], max_length=10),
        ),
        migrations.AlterField(
            model_name='forumreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to='app.userdata'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to='app.userdata'),
        ),
        migrations.AlterField(
            model_name='forumtag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='app.userdata'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='threads', to='api.forumtag'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.forumtopic'),
        ),
        migrations.AddIndex(
            model_name='forumlike',
            index=models.Index(fields=['user'], name='api_forumli_user_id_a9024a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumlike',
            index=models.Index(fields=['thread', 'like_type'], name='api_forumli_thread__0524b9_idx'),
        ),
        migrations.AddIndex(
            model_name='forumlike',
            index=models.Index(fields=['reply', 'like_type'], name='api_forumli_reply_i_681b63_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['user'], name='api_forumre_user_id_cef5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['thread', 'is_deleted'], name='api_forumre_thread__03b3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['parent_reply'], name='api_forumre_parent__3dc9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['author'], name='api_forumre_author__26264e_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['is_solution'], name='api_forumre_is_solu_95f23a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['approval_status', 'is_deleted'], name='api_forumth_approva_0a6927_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['author'], name='api_forumth_author__9f9a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['topic'], name='api_forumth_topic_i_6b0de8_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['is_pinned'], name='api_forumth_is_pinn_5bd671_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['created_at'], name='api_forumth_created_dd2e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['is_active'], name='api_forumto_is_acti_e072a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumlike',
            constraint=models.UniqueConstraint(condition=models.Q(('thread__isnull', False)), fields=('user', 'thread', 'like_type'), name='unique_thread_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='forumlike',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', False)), fields=('user', 'reply', 'like_type'), name='unique_reply_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='forumreaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reply__isnull', True), ('thread__isnull', False)), models.Q(('reply__isnull', False), ('thread__isnull', True)), _connector='OR'), name='reaction_either_thread_or_reply'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='app.userdata'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.forumreply'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.forumthread'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_notifications', to='app.userdata'),
        ),
        migrations.AddIndex(
            model_name='forumnotification',
            index=models.Index(fields=['user', 'is_read'], name='api_forumno_user_id_ac6231_idx'),
        ),
        migrations.AddIndex(
            model_name='forumnotification',
            index=models.Index(fields=['created_at'], name='api_forumno_created_9e9db1_idx'),
        ),
    ]
