# Generated by Django 5.1.4 on 2025-05-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_forumthread_review_date_forumthread_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
