# Generated by Django 5.1.4 on 2025-05-13 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_forumthread_media_type_forumthread_media_url"),
        ("app", "0005_userdata_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_articles", to="app.userdata")),
                ("topic", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.knowledgebasetopic")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(max_length=255)),
                ("file_url", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="api.knowledgebasearticle")),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeBaseStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed", models.DateTimeField(auto_now=True)),
                ("article", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="api.knowledgebasearticle")),
            ],
        ),
    ]
