# Generated by Django 5.1.4 on 2025-05-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_knowledgebasetag_knowledgebasetopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='banner_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
