# Generated by Django 5.1.4 on 2025-05-09 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_passwordresettoken'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approve Content'), ('reject', 'Reject Content'), ('delete', 'Delete Content'), ('restore', 'Restore Content'), ('edit', 'Edit Content'), ('verify', 'Verify User'), ('unverify', 'Unverify User'), ('promote', 'Promote User'), ('demote', 'Demote User'), ('suspend', 'Suspend User'), ('unsuspend', 'Unsuspend User'), ('other', 'Other Action')], max_length=20)),
                ('content_type', models.CharField(choices=[('pda', 'PDA Submission'), ('thread', 'Forum Thread'), ('reply', 'Forum Reply'), ('user', 'User Account'), ('topic', 'Forum Topic'), ('tag', 'Forum Tag'), ('other', 'Other Content')], max_length=20)),
                ('content_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_identifier', models.CharField(help_text='Identifying information about the content', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('content_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
