# Generated by Django 5.1.4 on 2025-05-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_moderatoraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_image_url',
            field=models.CharField(blank=True, default='/images/avatars/default.png', max_length=255, null=True),
        ),
    ]
