# Generated by Django 5.1.4 on 2025-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdata_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
