# Generated by Django 5.1.4 on 2025-05-15 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userdata_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatoraction',
            name='content_type',
            field=models.CharField(choices=[('pda', 'PDA Submission'), ('thread', 'Forum Thread'), ('reply', 'Forum Reply'), ('user', 'User Account'), ('topic', 'Forum Topic'), ('tag', 'Forum Tag'), ('other', 'Other Content'), ('donation', 'Donation')], max_length=20),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_payment_id', models.CharField(max_length=100, unique=True)),
                ('stripe_checkout_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='app.userdata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
