# Generated by Django 5.1.4 on 2025-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_moderatoraction_content_type_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='stripe_checkout_id',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='stripe_payment_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
