# Generated by Django 5.1.4 on 2025-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_stripe_checkout_id_donation_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='billing_city',
            field=models.CharField(blank=True, help_text='Billing address city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='billing_postal_code',
            field=models.CharField(blank=True, help_text='Billing address postal/zip code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='card_expiry_month',
            field=models.CharField(blank=True, help_text='Card expiry month (MM)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='card_expiry_year',
            field=models.CharField(blank=True, help_text='Card expiry year (YYYY)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='card_number_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of card number', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='card_type',
            field=models.CharField(blank=True, help_text='Type of card (Visa, Mastercard, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='gift_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='gift_recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='gift_recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, help_text='Administrative notes about this donation', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method_type',
            field=models.CharField(blank=True, help_text='Type of payment method used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='project_allocation',
            field=models.CharField(blank=True, help_text='Specific project the donation is for', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='refunded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
